### ISSUE TITLE
Speech synthesis locale gets out of sync with controls

### ISSUE THREAD

**Issue by chrisklus** [phetsims/number-play#152]
Discovered by a partner teacher and @Nancy-Salpepi in https://github.com/phetsims/number-play/issues/134#issuecomment-1066120855 - when the screens change, the speech synthesis language does not necessarily match the locale toggle on the new screen. This is because there's a control for the locale on each screen, but only one global setting for the speech locale.

**Comment by chrisklus** [comment]
This was completed in the above commit, closing.

**Comment by chrisklus** [comment]
Also tagging https://github.com/phetsims/number-play/issues/31

**Comment by Nancy-Salpepi** [comment]
This issue seems to be happening again with mac + safari, but only when switching to the compare screen from either screen 1 or 2. 

Steps:
1. Add ?secondLocale=es to url
2. Go to screen one and switch to Espanol
3. Press the Megaphone button
4. Switch to the compare screen and press the Megaphone button -- it will speak in Spanish even though the toggle is set to English

https://user-images.githubusercontent.com/87318828/181820195-db1ad2c2-e2c0-4a80-9687-a597898a0066.mov


It also happens in the other direction. 
1. Go to the Compare screen and toggle to Espanol. 
2. Press the Megaphone button--the statement is read in Spanish
3. Go to screen 1 or 2 and press the Megaphone button--the number is read in English
4. Go back to the Compare screen and press the Megaphone button-- it is the English voice speaking in Spanish

**Comment by Nancy-Salpepi** [comment]
I went back and tested 1.0.0-rc.1 again since I have updated my macOS and safari, and that version is working correctly.

**Comment by KatieWoe** [comment]
I repeated this on Win 11 Chrome. The correct words are read, but the wrong voice is used.

**Comment by KatieWoe** [comment]
This also occurs with the `?readAloud` parameter.

**Comment by stemilymill** [comment]
I've gotten the same as Katie but with Win10 chrome

**Comment by KatieWoe** [comment]
I wasn't able to reproduce on Win 11 Firefox due to https://github.com/phetsims/number-play/issues/160.

**Comment by Nancy-Salpepi** [comment]
With the Chromebook, I am seeing what @KatieWoe reported in https://github.com/phetsims/number-play/issues/152#issuecomment-1201524007

**Comment by marlitas** [comment]
@jessegreenberg and I looked at this issue and were not able to reproduce because NumberCompare was moved out into it's own sim. We did not notice any speech synthesis bugs in switching between screens in NumberPlay. @jessegreenberg mentioned that if another screen using speech synthesis is added to NumberCompare code from https://github.com/phetsims/number-play/commit/00f7ac19ed11452c111cd005b2d805f67f3f6ece will need to be added in `number-compare-main` as well. One way to do this may be to create a common NumberSuite sim that NumberCompare and NumberPlay extend from.

@Nancy-Salpepi can you confirm on your end wether you're able to reproduce something akin or not?

**Comment by Nancy-Salpepi** [comment]
@marlitas I'm not sure what is happening, but with mac + safari when I try to set the second locale, the sim freezes with this error:
<img width="1078" alt="Screenshot 2023-01-17 at 9 02 17 AM" src="https://user-images.githubusercontent.com/87318828/212919131-a88a95ee-29d9-4056-8c77-5e43edf3ff42.png">

When using mac + chrome, I can add the second locale and didn't notice any speech synthesis bugs.

**Comment by jessegreenberg** [comment]
OK https://github.com/phetsims/number-play/issues/204 is resolved, @Nancy-Salpepi sorry - should be able to test this again.

**Comment by Nancy-Salpepi** [comment]
Things look to be working correctly when switching between locales. I tested on the mac/iPad + safari. 
However, sometimes the sim freezes when trying to add a second locale--see issue https://github.com/phetsims/number-play/issues/205

**Comment by marlitas** [comment]
https://github.com/phetsims/number-play/issues/205 is fixed and closed so I think this is also en-route to closure. @chrisklus  back to you to confirm.

**Comment by chrisklus** [comment]
Just noting that #205 isn't fixed but I closed because it is being tracked in https://github.com/phetsims/number-suite-common/issues/13.

Thanks @Nancy-Salpepi @KatieWoe @jessegreenberg @marlitas for working on this! I think we are good to close.
